server:
  port: 8090

spring:
#  main:
#    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: gannima0.++-
    url: jdbc:postgresql://14.103.177.146:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    mcp:
      client:
        request-timeout: 180s
        stdio:
          servers-configuration: classpath:/config/mcp-servers-config-4.json
    ollama:
      base-url: http://14.103.177.146:11434
      chat:
        model: deepseek-r1:1.5b
      embedding:
        options:
          num-batch: 768
        model: nomic-embed-text
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-qIRy40akM1hUPLRe7eEf11F42aEd41088a9aE741C67a9459
      chat:
        options:
          model: gpt-4.1-mini
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
#    rag:
#      embed: nomic-embed-text #nomic-embed-text、text-embedding-ada-002

# Redis
redis:
  sdk:
    config:
      host: 14.103.177.146
      port: 16379
      password: gannima0.++-
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
